version: "3.8"
services:
  host:
    build:
      context: .
      dockerfile: Dockerfile.host
    ports:
      - "4000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  products:
    build:
      context: .
      dockerfile: Dockerfile.products
    environment:
      - API_URL=https://mscoreapi.azurewebsites.net/api
    ports:
      - "4001:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
